name: Deploy Node Application

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4
      - name: Login to docker hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - name: Build Docker Image
        run: docker build -t lakshyapandora22/paymentwebapp-backend
      - name: Publish Image to docker hub
        run: docker push lakshyapandora22/paymentwebapp-backend:latest

  deploy:
    needs: build
    runs-on: self-hosted
    steps:
    - name: Pull image from docker hub
      run: docker pull lakshyapandora22/paymentwebapp-backend:latest
    - name: Run Docker container
      run: docker run -d -p 3000:3000 --name nodejs-app-container -e CONNECTION_STRING='${{ secrets.CONNECTION_STRING }}' JWT_SECRET='${{ secrets.JWT_SECRET }}'